<!DOCTYPE html>
<html lang="en" class="light-style layout-menu-fixed" dir="ltr" data-theme="theme-default"
    data-assets-path="<?php echo base_url(); ?>assets/sneat/" data-template="vertical-menu-template-free">

<head>
    <meta charset="utf-8" />
    <meta name="viewport"
        content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0" />

    <title>Laporan Presensi Pegawai</title>

    <meta name="description" content="Laporan Presensi Pegawai" />

    <!-- Favicon -->
    <link rel="icon" type="image/x-icon" href="<?= site_url('assets/icon/siap32.png') ?>" />

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
        href="https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap"
        rel="stylesheet" />

    <!-- Bootstrap Core Css -->
    <link href="<?= site_url('assets/plugins/bootstrap/css/bootstrap.css') ?>" rel="stylesheet">

    <!-- Custom Css -->
    <link href="<?= site_url('assets/css/style.css') ?>" rel="stylesheet">

    <!-- print style overrides -->
    <link rel="stylesheet" media="print" href="<?= site_url('assets/css/print.css') ?>" />

    <!-- AdminBSB Themes. You can choose a theme from css/themes instead of get all themes -->
    <link href="<?= site_url('assets/css/themes/all-themes.css') ?>" rel="stylesheet" />

    <style>
        .telat {
            color: red !important;
            /* Optional: to ensure text is readable */
        }

        .hijau {
            background-color: teal !important;
        }

        @media print {
            .telat {
                color: red !important;
                /* Optional: to ensure text is readable */
            }

            .hijau {
                background-color: teal !important;
            }

            .page-break-after {
                page-break-after: always;
                /* Page break setelah elemen */
            }
        }
    </style>

</head>

<body>
    <!-- Main content -->
    <section class="mt-40">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <h5 class="font-underline align-center">REKAP PRESENSI PEGAWAI</h5>
                    <h4 class="align-center">MAHKAMAH SYAR'IYAH BANDA ACEH
                    </h4>
                </div>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <?php
                        $current_fullname = '';

                        foreach ($presensi as $record) {
                            if ($current_fullname !== $record->fullname) {
                                if ($current_fullname !== '') {
                                    echo '</tbody></table>';
                                }

                                $current_fullname = $record->fullname;
                                echo '<h5>' . $current_fullname . '</h5>';
                                echo '<table class="table table-bordered table-hover page-break-after">
                    <thead class="hijau">
                        <tr>
                            <th>Tanggal</th>
                            <th>Presensi Masuk</th>
                            <th>Presensi Pulang</th>
                            <th>Keterangan</th>
                        </tr>
                    </thead>
                    <tbody>';
                            }

                            echo '<tr>
                <td>' . $record->tgl . '</td>
                <td>' . $record->masuk . '</td>
                <td>' . $record->pulang . '</td>
                <td>' . $record->ket . '</td>
              </tr>';
                        }

                        if ($current_fullname !== '') {
                            echo '</tbody></table>';
                        }
                        ?>

                    </div>
                </div>
            </div>
            <i>Generated by </i>LITERASI MS BANDA ACEH<i> (<?= date('Y-m-d H:i:s')?>)</i>
        </div>
    </section>
    <!-- /.content -->

    <!-- Core JS -->

    <script>
        window.onload = function () {
            window.print();
        };
    </script>

</body>

</html>